version: 2
updates:
  # Main application
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - "dependabot :robot:"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 14
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependabot :robot:"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 14
